name: PR CI

on:
  pull_request:
    branches:
      - mealie-next
  merge_group:
    types: [checks_requested]
    branches:
      - mealie-next

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.merge_group.head_ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/test-backend.yml

  frontend-tests:
    name: "Frontend Tests"
    uses: ./.github/workflows/test-frontend.yml

  container-scanning:
    name: "Trivy Container Scanning"
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/partial-trivy-container-scanning.yml

  code-ql:
    name: "CodeQL"
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  build-package:
    name: "Build Python package"
    uses: ./.github/workflows/build-package.yml
    with:
      tag: e2e

  end-to-end:
    name: "End-to-End Tests"
    needs: build-package
    uses: ./.github/workflows/e2e.yml

  publish-image:
    name: "Publish PR Image"
    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'build-image') &&
      github.repository == 'abdo14m1/mealie'
    permissions:
      contents: read
      packages: write
    needs: build-package
    uses: ./.github/workflows/publish.yml
    with:
      tag: pr-${{ github.event.pull_request.number }}
